### ISSUE TITLE
Test Impact Analysis Framework

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10660]
## Description

Test Impact Analysis Framework (TIAF) is a means to identify what tests are required to run for a given code change (so we can run a subset of tests for a particular change instead of running all the tests as we do now). This has the potential to be a significant saving in terms of developer time and compute resources.

## Links

**Comment by jonawals** [comment]
- [ ]  - https://github.com/o3de/o3de/pull/15162
- [ ]  - https://github.com/o3de/o3de/pull/14956
- [ ]  - https://github.com/o3de/o3de/pull/14829
- [ ] - https://github.com/o3de/o3de/pull/14494
- [ ] - https://github.com/o3de/o3de/pull/14440
- [ ] - https://github.com/o3de/o3de/pull/14417
- [ ] - https://github.com/o3de/o3de/pull/14332
- [ ] - https://github.com/o3de/o3de/pull/14294
- [ ] - https://github.com/o3de/o3de/pull/14290
- [ ] - https://github.com/o3de/o3de/pull/14208
- [ ] - https://github.com/o3de/o3de/pull/13255
- [ ] - https://github.com/o3de/o3de/pull/13120
- [ ] - https://github.com/o3de/o3de/pull/13083
- [ ] - https://github.com/o3de/o3de/pull/13066
