### ISSUE TITLE
Animation support for common third party tools: Phase 2 - Asset import improvements

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#12387]
This separate Roadmap item is to divide the remaining work needed for further fixes/improvements to the animation import process.

With the initial delivery of root motion extraction complete, the character team has returned to addressing several small pain points concerning animation import issues and usability problems. This work is combining with input from UX, the DTs and QA to help harden and polish workflows in the animation editor.

**Comment by hultonha** [comment]
Relates to https://github.com/o3de/o3de/issues/10661

**Comment by hultonha** [comment]
This body of work has been completed.

**Comment by hultonha** [comment]
- [x] https://github.com/o3de/o3de/pull/13357
- [x] https://github.com/o3de/o3de/pull/12516
- [x] https://github.com/o3de/o3de/pull/12441
- [x] https://github.com/o3de/o3de/pull/12008
