### ISSUE TITLE
Add support for reduced coordinate articulations V1

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#15214]
[Migrated from JIRA LYN-18044]

### Summary

To deliver a robust and stable robotic arm/manipulator solution, articulation support needs to be added to O3DE. Reduced coordinate articulations are required for robotics simulation.

Initially hinge and prismatic joint types will be supported with reduced coordinate articulations.

### Focus

 - Actuation & sensors API,  basic configuration through properties (limits and such, on par with current joints). Support for hinge joints.

```[tasklist]
### Tasks

- [x] https://github.com/o3de/o3de/issues/15315
- [x] https://github.com/o3de/o3de/issues/15216
- [x] https://github.com/o3de/o3de/issues/15215
- [x] https://github.com/o3de/o3de/issues/15217
- [x] https://github.com/o3de/o3de/issues/15218
- [x] https://github.com/o3de/o3de/issues/15219
- [x] https://github.com/o3de/o3de/issues/15220
- [x] https://github.com/o3de/o3de/issues/15221
- [x] https://github.com/o3de/o3de/issues/15222
- [x] https://github.com/o3de/o3de/issues/15233
- [x] https://github.com/o3de/o3de/issues/15317
- [x] https://github.com/o3de/o3de/issues/15228
- [x] https://github.com/o3de/o3de/issues/15496
```

### Tasks

- [x] https://github.com/o3de/o3de/issues/15315
- [x] https://github.com/o3de/o3de/issues/15216
- [x] https://github.com/o3de/o3de/issues/15215
- [x] https://github.com/o3de/o3de/issues/15217
- [x] https://github.com/o3de/o3de/issues/15218
- [x] https://github.com/o3de/o3de/issues/15219
- [x] https://github.com/o3de/o3de/issues/15220
- [x] https://github.com/o3de/o3de/issues/15221
- [x] https://github.com/o3de/o3de/issues/15222
- [x] https://github.com/o3de/o3de/issues/15233
- [x] https://github.com/o3de/o3de/issues/15317
- [x] https://github.com/o3de/o3de/issues/15228
- [x] https://github.com/o3de/o3de/issues/15496

**Comment by hultonha** [comment]
All contained work for articulations V1 has been completed, closing issue.
