### ISSUE TITLE
Update spawnable asset to handle articulation hierarchy

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#15224]
[Migrated from JIRA LYN-18047]

### Summary

This work will make use of prefab processors in the pipeline to support this change.

```[tasklist]
### Tasks
- [x] https://github.com/o3de/o3de/issues/15225
- [x] https://github.com/o3de/o3de/issues/15229
- [x] https://github.com/o3de/o3de/issues/15230
```

### Tasks

- [x] https://github.com/o3de/o3de/issues/15225
- [x] https://github.com/o3de/o3de/issues/15229
- [x] https://github.com/o3de/o3de/issues/15230
