### ISSUE TITLE
Add support for reduced coordinate articulations V2

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#15232]
[Migrated from JIRA LYN-18241]

### Summary

To deliver a robust and stable robotic arm/manipulator solution, articulation support needs to be added to O3DE. Reduced coordinate articulations are required for robotics simulation.

This section of work follows on from https://github.com/o3de/o3de/issues/15214

```[tasklist]
### Tasks
- [ ] https://github.com/o3de/o3de/issues/15234
- [ ] https://github.com/o3de/o3de/issues/15235
- [ ] https://github.com/o3de/o3de/issues/15236
- [x] https://github.com/o3de/o3de/issues/15237
- [ ] https://github.com/o3de/o3de/issues/15226
- [ ] https://github.com/o3de/o3de/issues/15227
```

### Tasks

- [ ] https://github.com/o3de/o3de/issues/15234
- [ ] https://github.com/o3de/o3de/issues/15235
- [ ] https://github.com/o3de/o3de/issues/15236
- [x] https://github.com/o3de/o3de/issues/15237
- [ ] https://github.com/o3de/o3de/issues/15226
- [ ] https://github.com/o3de/o3de/issues/15227
