### ISSUE TITLE
[Release Day] Execute Launch for O3DE 23.05.0

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/o3de#15621]
- Predecessor Task: https://github.com/o3de/o3de/issues/15064

On Release Day, confirm each of the following launch activities is completed as expected:

```[tasklist]
### Release Team
- [x] [@Naomi-Wash ] Confirm all members of the release team are in attendance and available for the launch 10:30am Pacific:
  - [x] \[@naomi-wash and @tonybalandiuk ] - Acting Release Manager
  - [x] \[@cgalvan - @AMZN-alexpete] - Responsible for Merge
  - [x] \[@amzn-changml] - Responsible for applying the 23.05.0 version number (Release Tag), and publishing the version number update to o3debinaries.org
  - [x] \[@chanmosq]- Responsible for (1) merging the docs (2) updating/verifying both Windows and Linux text to show 23.05.0 on (<https://www.o3de.org/download/>)
  - [x] \[@Ulrick28] - Responsible for main branch verification
  - [x] \[@AMZN-Dk] - Responsible for installer and o3debinaries.org verification
```

```[tasklist]
### Launch Prerequisites
- [x] [@naomi-wash] Confirm the following pre-requisites are complete:
  - [ ] o3de/sig-release#159
  - [ ] o3de/sig-release#160
```

```[tasklist]
### Merge of Stabilization to Main
- [x] Execute the following steps:
  - [x] \[@AMZN-Dk] Confirm the following pre-requisites are complete:
    - [x] o3de/sig-release#161
    - [x] o3de/sig-release#162
  - [x] \[@cgalvan - @AMZN-alexpete] Click the Merge button on the PR (via. GitHub) for all of the following 5 repos:
    - [x] o3de:
    - [x] o3de-multiplayersample:
    - [x] o3de-multiplayersample-assets
    - [x] o3de-netsoaktest:
    - [x] o3de-extras
```

```[tasklist]
### Installers
- [x] [@AMZN-Dk] Confirm the following pre-requisites are complete:
  - [ ] o3de/sig-release#163
```

```[tasklist]
### Release Tag
-  [x] [@amzn-changml] Create the release tag [23.05.0], and apply it to the following repos:
  - [x] o3de
  - [x] o3de-multiplayersample
  - [x] o3de-multiplayersample-assets
  - [x] o3de-netsoaktest
  - [x] o3de-extras
- [x] [@amzn-changml] Begin work to add LFS binary objects to the artifacts under the new release tag, per the steps documented in this issue:
- [ ] o3de/sig-release#168
```

```[tasklist]
### Docs Updates
-  [x] [@AMZN-Dk] Confirm the following pre-requisites are complete:
  - [ ] o3de/sig-release#164
  - [ ] o3de/sig-release#165
  - [ ] o3de/sig-release#166
  - [ ] o3de/sig-release#167
- [x] [@chanmosq] Merge PR for applying the generated API reference to the docs site
- [x] [@chanmosq] Merge PR for bumping the version number in the Linux install instructions
- [x] [@chanmosq] Merge PR for docs from stabilization to main (includes release notes and update to o3de.org download screen version number)
- [x] [@chanmosq] Re-target open PRs against stabilization against development
```

```[tasklist]
###Website Updates for binaries

- [x] o3debinaries.org
  - [x] \[@AMZN-Dk] Confirm the following pre-requisite is complete: stage website update
  - [x] \[@amzn-changml] Publish version number update to o3debinaries.org
```

```[tasklist]
### Verification

  - [x] [@Ulrick28]  Confirm the [main branch](https://github.com/o3de/o3de/tree/main) has the latest code on Github
  - [x] [@amzn-changml]  Confirm the release tag is applied to main branch
  - [x] [@Ulrick28]  Confirm the mainline build has begun (it should auto-start)
  - [x] [@AMZN-Dk]  Confirm the version number is updated on o3debinaries.org
  - [x] [@Ulrick28]  Confirm the Windows installer is the correct version by downloading it from o3debinaries.org
  - [x] [@AMZN-Dk]  Confirm the Linux debian package is the correct version by downloading it from o3debinaries.org
  - [x] [@Ulrick28]  Confirm the installed Windows editor shows the correct version on the splash screen
  - [x] [@AMZN-Dk]  Confirm the installed Linux editor shows the correct version on the splash screen
  - [x] [@Ulrick28] Confirm the version number is updated on o3de.org downloads page (Required for Major Releases only)
  - [x] [@Ulrick28] Confirm the release notes are updated
```

**Comment by Naomi-Wash** [comment]
@vincent6767 I updated the repos to the following:
o3de: 
o3de-multiplayersample: 
o3de-multiplayersample-assets
o3de-netsoaktest: 
o3de-extras
