### ISSUE TITLE
AWS Gems ScriptCanvas nodes lack proper input titles

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de#4502]
Multiple script canvas nodes associated with the AWS Gems (e.g., ClientAuth, Metrics) lack proper input titles, instead listing generic types like "String 0". Example:

![image](https://user-images.githubusercontent.com/34254888/136084855-5ae8d3e7-8ea6-479e-9b28-c721ea990854.png)

This issue is intended to identify where such gaps exist, as they are discovered, and progress in fixing them.

### Tasks

- [ ] Add missing field titles + tool tips to AWSClientAuth 
     * https://github.com/o3de/o3de/pull/4451
     * https://github.com/o3de/o3de/pull/4613
- [x] Add missing field titles + tooltips to AWSMetrics **[in progress]**
     * https://github.com/o3de/o3de/pull/4534
- [ ] audit AWSCore gem for missing input labels
- [ ] audit node explorer context menu names / appearance

**Comment by rainbj** [comment]
We have sat down and worked out the short and long term plan. UX is ok to merge changes

**Comment by guillaume-haerinck** [comment]
resolved by pr above
