### ISSUE TITLE
[Release Day] Execute Launch

### ISSUE THREAD

**Issue by forhalle** [o3de/o3de#6635]
- Predecessor Task: [Planning] Prepare for Launch (#6928)

On Release Day, confirm each of the following launch activities is completed as expected:

- Release Team
   - [x] [@forhalle] Confirm all members of the release team are in attendance and available for the launch:
      - [x] [@forhalle] - Release Manager
      - [x] [@cgalvan] - Responsible for Merge
      - [x] [@amzn-changml] - Responsible for Release Tag, and publishing the versoin number update to o3debinaries.org
      - [x] [@sptramer, backup: Finite_State] - Responsible for applying release tag to docs site, and publishing/verifying Release Notes 
      - [x] [@Ulrick28] - Responsible for main branch verification
      - [x] [@AMZN-Dk] - Responsible for installer and o3debinaries.org verification
- Launch Prerequisites
   - [x] [@forhalle] Confirm the following pre-requistes are complete:
      - [x] [#6781]
      - [x] [#6793]
- Merge of Stabilization to Main
   - [ ] Execute the following steps:
      - [x] [@forhalle] Confirm the following pre-requisites are complete:
         - [x] [#6992]
         - [x] [#6634]
      - [x] [@cgalvan] Click the Merge button on the PR (via. GitHub) for all of the following 5 repos:
         - [x] o3de: [#7120]
         - [x] o3de-atomtest: [PR]  (Not needed for 21.11.2)
         - [x] o3de-atom-sampleviewer: [PR]  (Not needed for 21.11.2)
         - [x] o3de-multiplayersample: [PR]  (Not needed for 21.11.2)
         - [x] o3de-netsoaktest: [PR]  (Not needed for 21.11.2)
- Installers
   - [x] [@forhalle] Confirm the following pre-requisites are complete:
      - [x] [#7019]
- Release Tag
   - [x] [@amzn-changml] Create the release tag [2111.2], and apply it to the following repos:
        - [x] o3de
        - [x] o3de-atomtest
        - [x] o3de-atom-sampleviewer
        - [x] o3de-multiplayersample
        - [x] o3de-netsoaktest 
    - [x] [@amzn-changml] Begin work to add LFS binary objects to the artifacts under the new release tag, per the steps documented in this issue:
        - [#6933]
- Docs Updates
   - [x] [@forhalle] Confirm the following pre-requistes are complete:
      - [x] [#7205]
      - [x] [#7209]
   - [x] [@sptramer, backup: Finite_State] Merge PR for applying the generated API reference to the docs site [https://github.com/o3de/o3de.org/pull/1382]
   - [x] [@sptramer, backup: Finite_State] Merge PR for bumping the version number in the Linux install instructions [https://github.com/o3de/o3de.org/pull/1384]
- Website Updates
   - o3de.org (Required for Major Releases only; Skip for Point Releases)
      - [x] [@forhalle] Confirm the following pre-requisite is complete: [#7044] (Not needed for 21.11.2)
      - [x] [Resource Name] Publish version number update to o3de.org (Not needed for 21.11.2)
   - o3debinaries.org
      - [x] [@forhalle] Confirm the following pre-requisite is complete: [#7020]
      - [x] [@amzn-changml] Publish version number update to o3debinaries.org
   - Release Notes
      - [x] [@forhalle] Confirm the following pre-requisite is complete: [#6926]
      - [x] [@sptramer, backup: Finite_State] Publish the Release Notes  
- Verification
   - [x] [@Ulrick28] Confirm the [main branch](https://github.com/o3de/o3de/tree/main) has the latest code on Github 
   - [x] [@amzn-changml] Confirm the release tag is applied to main branch
   - [x] [@Ulrick28] Confirm the mainline build has begun (it should auto-start)
   - [x] [@AMZN-Dk] Confirm the version number is updated on o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the Windows installer is the correct version by downloading it from o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the Linux debian package is the correct version by downloading it from o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the installed Windows editor shows the correct version on the splash screen
   - [x] [@AMZN-Dk] Confirm the installed Linux editor shows the correct version on the splash screen
   - [x] [Resource Name] Confirm the version number is updated on o3de.org (Required for Major Releases only; Skip for Point Releases) (Not needed for 21.11.2)
   - [x] [@sptramer, backup: Finite_State] Confirm the release notes are updated

**Comment by forhalle** [comment]
I'm meeting with @Ulrick28 and @tonybalandiuk later today to identify owners for each item in this task list, and to confirm if we should include owners and tasks for non-release blocking work (e.g. marketing blogs, etc.)

**Comment by forhalle** [comment]
All launch day activities noted above are complete!
