### ISSUE TITLE
Linux Client Runtime

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#745]
### Description
Linux support for O3DE includes three core capabilities: a dedicated server runtime, application client runtime, and editing tools. This issue specifically covers the tasks that are planned to support targeting a Linux client runtime.  

### Current status
The Vulkan RHI is currently disabled for Linux. The team is in the process of enabling this functionality to support the new Atom renderer. Additional tasks will implement native window and input functionality for Linux client applications built with O3DE. 

### Tasks
**Assigned work**
- [ ] Investigate client asset processing on Linux 
- [ ] Enable Atom Vulkan RHI
- [ ] Add Linux as a supported target platform in Asset Processor
- [ ] Implement native window functionality, including full screen support, styles, and resizing
- [ ] Add support for input on Linux client applications
- [ ] Ensure compiled Project.GameLauncher crashes are resolved
- [ ] Implement save data for Linux
 
**Unassigned work**
- [ ] Fix failing native window tests for Linux
- [ ] Fix failing input tests for Linux
- [ ] Fix failing Atom RPI tests for Linux
- [ ] Fix failing save data tests for Linux

**Comment by chuyuanzheng3** [comment]
We has enable RHI/native window(Excluding full screen)/Gamelauncher compile， how can we working with you?

**Comment by iMonZ** [comment]
Will the Wayland display server be fully supported?

**Comment by spham-amzn** [comment]
> Will the Wayland display server be fully supported?

Xcb will be implemented first, but we will probably need an RFC to expand linux to support wayland as well

**Comment by iMonZ** [comment]
That’s sad. 
Since Wayland is very important for the future and X11 will be step by step deprecated. It’s more important to focus on Wayland development since nearly every distro already switched

**Comment by ryliejamesthomas** [comment]
> nearly every distro already switched

Well that's not true at all. Supporting is not the same as switching.

**Comment by AMZN-Liv** [comment]
This has been included in 2111.1 and is available as of today!
