### ISSUE TITLE
Editor View Bookmarks

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#8435]
# Description

Add support for View Bookmarks to be stored in the O3DE Editor

Please see this RFC for more details - https://github.com/o3de/sig-content/issues/38 (issue + discussion), https://github.com/o3de/sig-content/blob/main/rfcs/rfc-38-View-Bookmarks.md (RFC).

- [x] Restore existing function key save/restore functionality (`Ctrl+F<num>` - save, `Shift+F<num>` - load)
- [ ] Expose View Bookmarks to UI (e.g. viewport border camera UI section) - _in progress_
- [ ] Add support for Editor Component View  Bookmarks (sharable) - _in progress_

### Related Work

https://github.com/o3de/o3de/pull/7855
https://github.com/o3de/o3de/pull/8400
https://github.com/o3de/o3de/pull/8434
