### ISSUE TITLE
[Release Day] Execute Launch for O3DE 22.05.0

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/o3de#9255]
- Predecessor Task: [Planning] Prepare for Launch (#6928)

On Release Day, confirm each of the following launch activities is completed as expected:

- Release Team
   - [x] [@tonybalandiuk ] Confirm all members of the release team are in attendance and available for the launch 10:30am Pacific:
      - [x] [@tonybalandiuk ] - Release Manager
      - [x] [@cgalvan] - Responsible for Merge
      - [x] [@amzn-changml] - Responsible for Release Tag, and publishing the version number update to o3debinaries.org
      - [x] [@micronAMZN ] - Responsible for applying release tag to docs site, and publishing/verifying Release Notes 
      - [x] [@Ulrick28] - Responsible for main branch verification
      - [x] [@AMZN-Dk] - Responsible for installer and o3debinaries.org verification
      - [x] khahil (LF) - Responsible for website going live
- Launch Prerequisites
   - [x] [@tonybalandiuk ] Confirm the following pre-requistes are complete:
      - [x] [#9253]
      - [x] [#9268]
- Merge of Stabilization to Main
   - [x] Execute the following steps:
      - [x] [@tonybalandiuk ] Confirm the following pre-requisites are complete:
         - [x] [#9258 ]
         - [x] [#9265 ]
      - [x] [@cgalvan] Click the Merge button on the PR (via. GitHub) for all of the following 5 repos:
         - [x] o3de: https://github.com/o3de/o3de/pull/9458
         - [x] o3de-atomtest: https://github.com/o3de/o3de-atomtest/pull/85
         - [x] o3de-atom-sampleviewer: https://github.com/o3de/o3de-atom-sampleviewer/pull/442
         - [x] o3de-multiplayersample: https://github.com/o3de/o3de-multiplayersample/pull/145
         - [x] o3de-netsoaktest: https://github.com/o3de/o3de-netsoaktest/pull/23
- Installers
   - [x] [@tonybalandiuk ] Confirm the following pre-requisites are complete:
      - [x] [#9259 ]
- Release Tag
   - [x] [@amzn-changml] Create the release tag [22.05.0], and apply it to the following repos:
        - [x] o3de
        - [x] o3de-atomtest
        - [x] o3de-atom-sampleviewer
        - [x] o3de-multiplayersample
        - [x] o3de-netsoaktest 
    - [x] [@amzn-changml] Begin work to add LFS binary objects to the artifacts under the new release tag, per the steps documented in this issue:
        - [#9270 ]
- Docs Updates
   - [x] [@tonybalandiuk ] Confirm the following pre-requistes are complete:
      - [x] [#9256 ]
      - [x] [#9257 ]
   - [x] [@micronAMZN ] Merge PR for applying the generated API reference to the docs site [https://github.com/o3de/o3de.org/pull/1605]
   - [x] [@micronAMZN] Merge PR for bumping the version number in the Linux install instructions [https://github.com/o3de/o3de.org/pull/1617] 
- Website Updates
   - o3de.org (Required for Major Releases only; Skip for Point Releases)
      - [x] [@tonybalandiuk ] Confirm the following pre-requisite is complete: [#9267 ]
      - [x] [@theheels] Publish website update to o3de.org  [https://github.com/o3de/o3de.org/pull/1626 ])
   - o3debinaries.org
      - [x] [@tonybalandiuk ] Confirm the following pre-requisite is complete: [#9254 ]
      - [x] [@amzn-changml] Publish version number update to o3debinaries.org 
   - Release Notes
      - [x] [@tonybalandiuk] Confirm the following pre-requisite is complete: [#9263 ]
      - [x] [@micronAMZN ] Publish the Release Notes   https://github.com/o3de/o3de.org/pull/1607
- Verification
   - [x] [@Ulrick28] Confirm the [main branch](https://github.com/o3de/o3de/tree/main) has the latest code on Github 
   - [x] [@amzn-changml] Confirm the release tag is applied to main branch
   - [x] [@Ulrick28] Confirm the mainline build has begun (it should auto-start)
   - [x] [@AMZN-Dk] Confirm the version number is updated on o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the Windows installer is the correct version by downloading it from o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the Linux debian package is the correct version by downloading it from o3debinaries.org
   - [x] [@AMZN-Dk] Confirm the installed Windows editor shows the correct version on the splash screen
   - [ ] [@AMZN-Dk] Confirm the installed Linux editor shows the correct version on the splash screen
   - [x] [@Ulrick28] Confirm the version number is updated on o3de.org (Required for Major Releases only)
   - [x] [@Ulrick28] Confirm the release notes are updated

**Comment by tonybalandiuk** [comment]
per @AMZN-Dk  "Linux installer is showing correct version, however the Editor Splash screen is showing "Development Build" instead of Release 22.05.0 when loading. This does not occur on Windows build...I don't think this is a show stopper issue but we are getting a issue entered for it"

**Comment by tonybalandiuk** [comment]
issue opened for Linux splash screen https://github.com/o3de/o3de/issues/9519

**Comment by tonybalandiuk** [comment]
resolving. 1 outstanding issue to be resolved post-lauch. see above
